In [4]:
import pandas as pd
import sys
import os
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from sklearn import metrics
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeClassifier
from statsmodels.stats.stattools import durbin_watson
#from aif360.metrics import ClassificationMetric
from statsmodels.tsa.api import ExponentialSmoothing, SimpleExpSmoothing, Holt
from sklearn.model_selection import train_test_split
df = pd.read_csv(r"travel insurance.csv")
df = df[:50000]
df.head()
df["Distribution Channel"] = np.where(df["Distribution Channel"] == "Offline", 0., 1.)
df["Agency Type"] = np.where(df["Agency Type"] == "Travel Agency", 0., 1.)
df["Claim"] = np.where(df["Claim"] == "No", 0., 1.)
df['Age'] = df['Age'].astype(float)
df.head()


Agency Type  Distribution Channel  Claim  Duration  Net Sales  \
0          0.0                   0.0    0.0       186      -29.0   
1          0.0                   0.0    0.0       186      -29.0   
2          0.0                   1.0    0.0        65      -49.5   
3          0.0                   1.0    0.0        60      -39.6   
4          0.0                   1.0    0.0        79      -19.8   

   Commision (in value)   Age  
0                  9.57  81.0  
1                  9.57  71.0  
2                 29.70  32.0  
3                 23.76  32.0  
4                 11.88  41.0

In [9]:
#df_final = pd.DataFrame(columns=['Partition','R2','DW','E2','MSE','MAE','MAPE','Theil'])
X_NetSales = df.loc[:,df.columns.drop(['Net Sales'])]
y_NetSales = df['Net Sales']
X_NetSales.head()
for i in range(5,10):
 print(i/10)
 X_train, X_test, y_train, y_test = train_test_split(X_NetSales, y_NetSales, test_size=1-i/10,
random_state=42)
 regressor = LinearRegression()
 regressor.fit(X_train, y_train) #training the algorithm
 #To retrieve the intercept:
 print(regressor.intercept_)

 #df_final = df_final.append([[i/10,i/10,i/10,i/10,i/10,i/10,i/10,i/10]], ignore_index = True)
 #For retrieving the slope:
 print(regressor.coef_)
 y_pred = regressor.predict(X_test)
 y_test.to_numpy()
 df_res = pd.DataFrame({'Actual': y_test.to_numpy().flatten(), 'Predicted': y_pred.flatten()})
 df_res


 # df_final = df_final.append([[i/10,metrics.r2_score(y_test,
#y_pred) ,durbin_watson(y_test),np.sum(np.square(y_pred -y_test)),
 # metrics.mean_squared_error(y_test, y_pred), metrics.mean_absolute_error(y_test,
#y_pred),metrics.mean_absolute_percentage_error(y_test, y_pred),0]],
#columns=['Partition','R2','DW','SE2','MSE','MAE','MAPE','Theil'])
 print('R2:', metrics.r2_score(y_test, y_pred))
 print('DW:', durbin_watson(y_test))
 print('sum e 2:',np.sum(np.square(y_pred -y_test)))
 print('MSE:', metrics.mean_squared_error(y_test, y_pred))
 print('MAE:', metrics.mean_absolute_error(y_test, y_pred))
 print('RMSE:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))
 print('MAPE:', metrics.mean_absolute_percentage_error(y_test, y_pred))

#df_row
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))
print('MAPE:', metrics.mean_absolute_percentage_error(y_test, y_pred))
print('R2:', metrics.r2_score(y_test, y_pred))
print('DW:', durbin_watson(y_test))
print('sum e 2:',np.sum(np.square(y_pred -y_test)))
#print('sum e 2:',ClassificationMetric(y_pred -y_test))

0.5
20.054728810582574
[ 1.54218661  4.05420548 25.10528941  0.1373052   1.33514297 -0.10642226]
R2: 0.37593094150647344
DW: 1.1498326771854708
sum e 2: 31806734.79717726
MSE: 1272.2693918870903
MAE: 20.153168683810435
RMSE: 35.668885487033236
MAPE: 7039988190058832.0
0.6
22.714897958321078
[ 1.41726314  2.40361052 26.98684209  0.10531093  1.39781359 -0.10871528]
R2: 0.4002554882775098
DW: 1.144414872392941
sum e 2: 24453126.27346742
MSE: 1222.6563136733712
MAE: 20.401716150771232
RMSE: 34.96650273723941
MAPE: 7194593187377098.0
0.7
22.231377663705935
[ 1.38741302  2.68175212 27.5735825   0.10556609  1.40367288 -0.10181347]
R2: 0.38725364463993395
DW: 1.162050032611134
sum e 2: 19019608.008980848
MSE: 1267.8893413093026
MAE: 20.60037772479147
RMSE: 35.60743379280937
MAPE: 7686313616196454.0
0.8
23.451748210021233
[ 1.36302776  1.88319299 28.31361046  0.0928648   1.42099483 -0.10228972]
R2: 0.3890894179615242
DW: 1.1698185717905514
sum e 2: 12842690.474079795
MSE: 1284.2690474079795
MAE